# Семинар 1: знакомство с NumPy


## Немного про Jupyter notebook

Полная документация: https://devpractice.ru/python-lesson-6-work-in-jupyter-notebook/

---
В Jupyter Notebook есть два режима работы: режим _команд_ и режим _редактирования_

_Командный_ режим нужен для того, чтобы взаимодействовать и управлять ячейками (добавлять, удалять, запускать, копировать, ...)

В режиме _редактирования_ вы меняете содержимое ячейки. 

Ячейки бывают двух основных типов, _код_ и _разметка_

### Полезные команды

(находясь в командном режиме)

- `a` - добавить пустую ячейку сверху

- `b` - добавить пустую ячейку снизу
- `c` - скопировать текущую ячейку
- `v` - вставить скопированную ячейку
- `d` - удалить текущую ячейку
- `x` - вырезать (удалить и скопировать) текущую ячейку
- `m` - изменить тип выбранной ячейки на "разметка" 
- `y` - изменить тип выбранной ячейки на "код" 
- `z` - отменить последнее действие


- `Enter` - начать редактировать выбранную ячейку

(будучи в режим редактирования ячейки)
- `esc` - вернуться в командный режим

(будучи в любом режиме)

- `Ctrl + Enter` - запустить выбранную ячейку
- `Shift + Enter` - запустить выбранную ячейку и выбрать следующую

In [7]:
2 + 2

5

In [3]:
x = 1
print(x)

1


## numpy

- документация: http://www.numpy.org/

Библиотека numpy является удобным инструментом для работы с многомерными массивами с возможностью векторизации вычислений. Рассмотрим базовые вещи, которые можно делать с помощью нее.

In [4]:
import numpy as np

In [5]:
np.array

<function numpy.array>

In [20]:
vec = np.array([[1, 2], [3, 4], [5, 6]])

In [21]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
print(vec)

[[1 2]
 [3 4]
 [5 6]]


In [17]:
vec1 = np.array([[1, 2], [3, 4], [5.0, {}]])

С чем мы работаем?

In [22]:
vec.dtype

dtype('int32')

In [23]:
type(vec)

numpy.ndarray

Размер массива:

In [24]:
vec.shape

(3, 2)

Число осей:

In [25]:
vec.ndim

2

У некоторых функций бывает параметр `axis`, который позволяет применить эту функцию по разным осям - в данном случае, по строкам или столбцам:

In [26]:
np.sum(vec)

21

In [27]:
vec.sum()

21

In [29]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
np.sum(vec, axis=0)

array([ 9, 12])

In [31]:
np.sum(vec, axis=1)

array([ 3,  7, 11])

In [32]:
vec.sum()

21

Транспонируем массив:

In [33]:
vec.T

array([[1, 3, 5],
       [2, 4, 6]])

In [34]:
vec.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

Обратите внимание, что переменная `vec` не поменялась!

In [36]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

Размеры массивов можно менять:

In [39]:
vec.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
vec.reshape(-1, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
vec.reshape(2, -1)

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
vec.reshape(4, 2)

ValueError: cannot reshape array of size 6 into shape (4,2)

In [45]:
np.array([1, 2, 3]).reshape(-1, 1)

array([[1],
       [2],
       [3]])

In [47]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

Индексирование:

In [52]:
vec[:, 1]

array([2, 4, 6])

In [48]:
vec[2, :]

array([5, 6])

In [49]:
vec[1:2, 0]

array([3])

In [50]:
vec[::2, :]

array([[1, 2],
       [5, 6]])

И, наконец - арифметические операции!

In [53]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [78]:
vec + 1

array([[2, 3],
       [4, 5],
       [6, 7]])

In [55]:
vec * 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [56]:
vec**2

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

In [58]:
vec * vec

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

In [59]:
vec + vec**2

array([[ 2,  6],
       [12, 20],
       [30, 42]])

In [60]:
vec * vec**2

array([[  1,   8],
       [ 27,  64],
       [125, 216]])

In [61]:
np.sin(vec)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ]])

In [65]:
np.log(vec)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436],
       [1.60943791, 1.79175947]])

In [68]:
np.tan?

Signature:       np.tan(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'tan'>
File:            c:\users\artem\.conda\envs\default\lib\site-packages\numpy\__init__.py
Docstring:      
tan(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Compute tangent element-wise.

Equivalent to ``np.sin(x)/np.cos(x)`` element-wise.

Parameters
----------
x : array_like
    Input array.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array wil

Матричное умножение:

In [67]:
vec * vec

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

In [70]:
np.dot(vec, vec.T)

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

In [73]:
vec.shape, vec.T.shape

((3, 2), (2, 3))

In [74]:
vec.dot(vec**2)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [75]:
vec.dot((vec**2).T)

array([[  9,  41,  97],
       [ 19,  91, 219],
       [ 29, 141, 341]])

In [76]:
(vec**2).dot(vec.T)

array([[  9,  19,  29],
       [ 41,  91, 141],
       [ 97, 219, 341]])

In [77]:
vec @ (vec**2).T

array([[  9,  41,  97],
       [ 19,  91, 219],
       [ 29, 141, 341]])

Broadcasting:
https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html

In [93]:
vec.reshape(-1, -1, 2)

ValueError: can only specify one unknown dimension

In [81]:
vec + 1

array([[2, 3],
       [4, 5],
       [6, 7]])

In [84]:
vec + np.array([1, 1, 1, 1, 1, 1]).reshape(vec.shape)

array([[2, 3],
       [4, 5],
       [6, 7]])

In [85]:
vec[0, :]

array([1, 2])

In [86]:
vec - vec[0, :]

array([[0, 0],
       [2, 2],
       [4, 4]])

In [87]:
vec[0, :] - vec

array([[ 0,  0],
       [-2, -2],
       [-4, -4]])

In [90]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [91]:
np.arange(3).reshape(3, 1)

array([[0],
       [1],
       [2]])

In [89]:
vec - np.arange(3).reshape(3, 1)

array([[1, 2],
       [2, 3],
       [3, 4]])

In [92]:
np.exp(np.array([[1, 2], [3, 4]]))

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

Булевы массивы:

In [95]:
vec % 2 == 0

array([[False,  True],
       [False,  True],
       [False,  True]])

In [96]:
is_even = vec % 2 == 0
print(is_even)

[[False  True]
 [False  True]
 [False  True]]


In [97]:
np.sum(is_even)

3

Булевы массивы позволяют вытаскивать элементы с True из массива того-же размера

In [98]:
vec[vec % 2 == 0]

array([2, 4, 6])

In [103]:
vec[(vec % 2 == 0) & (vec == 6)]

array([6])

In [100]:
vec[vec == 6]

array([6])

In [104]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [105]:
np.where(vec % 2 == 0, vec // 2, vec * 5)

array([[ 5,  1],
       [15,  2],
       [25,  3]])

Иногда бывает полезно создавать специфичные массивы. Массив из нулей:

In [106]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

Массив из единиц:

In [112]:
np.ones((3, 2)) + 7

array([[8., 8.],
       [8., 8.],
       [8., 8.]])

Единичная матрица:

In [108]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [111]:
np.eye(2, 3)

array([[1., 0., 0.],
       [0., 1., 0.]])

Массивы можно объединять:

In [ ]:
vec

In [ ]:
np.hstack((vec, np.zeros(vec.shape)))

In [ ]:
np.vstack((vec, np.zeros(vec.shape)))

Генерация случайных чисел:

In [114]:
dir(np.random)

['BitGenerator',
 'Generator',
 'MT19937',
 'PCG64',
 'PCG64DXSM',
 'Philox',
 'RandomState',
 'SFC64',
 'SeedSequence',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_bounded_integers',
 '_common',
 '_generator',
 '_mt19937',
 '_pcg64',
 '_philox',
 '_pickle',
 '_sfc64',
 'beta',
 'binomial',
 'bit_generator',
 'bytes',
 'chisquare',
 'choice',
 'default_rng',
 'dirichlet',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_bit_generator',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_bit_generator',
 'set_state',
 'shuf

In [149]:
np.random.rand(2, 3)

array([[0.60999666, 0.83319491, 0.17336465],
       [0.39106061, 0.18223609, 0.75536141]])

In [156]:
np.random.seed(123)

In [157]:
x = 1

In [158]:
# np.random.seed(666)
np.random.rand(2, 3)

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646]])

In [159]:
np.random.rand(2, 3)

array([[0.9807642 , 0.68482974, 0.4809319 ],
       [0.39211752, 0.34317802, 0.72904971]])

In [142]:
np.random.seed(42)
np.random.rand(2, 3)

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452]])

In [143]:
np.random.randn(3, 2)

array([[ 1.57921282,  0.76743473],
       [-0.46947439,  0.54256004],
       [-0.46341769, -0.46572975]])

In [144]:
np.random.normal(2, 1, size=3)

array([2.24196227, 0.08671976, 0.27508217])

In [145]:
np.random.randint(5, 10, size=3)

array([7, 6, 8])

Почему вообще используют `numpy`?

In [160]:
n = 300
A = np.random.rand(n, n)
B = np.random.rand(n, n)

In [163]:
B.shape

(300, 300)

In [164]:
%%time
C = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        for k in range(n):
            C[i, j] += A[i, k] * B[k, j]

CPU times: total: 2.16 s
Wall time: 22.7 s


In [169]:
%%timeit
C = A @ B

1.56 ms ± 46.6 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


### Задания для самостоятельного решения

1. Развернуть одномерный массив (сделать так, чтобы его элементы шли в обратном порядке).
2. Найти максимальный нечетный элемент в массиве.
3. Замените все нечетные элементы массива на ваше любимое число.
4. Создайте массив первых n нечетных чисел, записанных в порядке убывания. Например, если `n=5`, то ответом будет `array([9, 7, 5, 3, 1])`. *Функции, которые могут пригодиться при решении: `.arange()`*
5. Вычислите самое близкое и самое дальнее числа к данному в рассматриваемом массиве чисел. Например, если на вход поступают массив `array([0, 1, 2, 3, 4])` и число 1.33, то ответом будет `(1, 4)`. _Функции, которые могут пригодиться при решении: `.abs()`, `.argmax()`, `.argmin()`_
6. Вычисляющую первообразную заданного полинома (в качестве константы возьмите ваше любимое число). Например, если на вход поступает массив коэффициентов `array([4, 6, 0, 1])`, что соответствует полиному $4x^3 + 6x^2 + 1$, на выходе получается массив коэффициентов `array([1, 2, 0, 1, -2])`, соответствующий полиному $x^4 + 2x^3 + x - 2$. _Функции, которые могут пригодиться при решении: `.append()`_
7. Пользуясь пунктом 6, посчитайте первую производную для заданного полинома в заданной точке.

In [ ]:
# ┌(▼▼メ)┘ └(メ▼▼)┐